### ISSUE TITLE
Adiantar numero sniic

### ISSUE THREAD

**Issue by leogermani** [culturagovbr/mapasculturais-br#18]
Aparecer na Infobox

Aparecer também no painel:
. no painel geral aparecer num sniic do agente padrão

.. Entre a saudação "Olá...." e as caixinhas "meus agentes, etc...", aparecer uma frase "O número SNIIC do seu agente padrão "NOME_DO_AGENTE" é XXXXXX

. nos paineis por tipo de entidade, aparecer num sniic na lista

**Comment by lfagundes** [comment]
Na Infobox parou de funcionar, voltei a tarefa para In Progress
