### ISSUE TITLE
Exportação de planilhas com metadados completos

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-br#19]
Endereço, geolocalização, telefones (mais de um numero de contato), emails (mais de um email de contato)

**Comment by leogermani** [comment]
Na verdade precisamos colocar todos os metadados que não forem privados

**Comment by marylly** [comment]
Correção da disponibilização dos metadados não privados nas exportação das planilhas das buscas sistema Mapas Culturais.
