### ISSUE TITLE
Destacar os campos obrigatórios no preenchimento da página do agente

### ISSUE THREAD

**Issue by dricaveloso** [culturagovbr/mapasculturais-br#20]
No preenchimento da página do agente destacar quais campos são obrigatórios para salvar e publicar pela primeira vez e quais podem ser preenchidos posteriormente.

Os campos obrigatórios podem estar marcados com *
Informar que os campos com * são obrigatórios.

**Comment by thaisrigolon** [comment]
Issue homologada.
